name: Test
on:
  push:
    branches: [main]
jobs:
  cli:
    runs-on: ubuntu-latest
    steps:
      - name: run cli
        run: gh api /repos/jayground8/poc/contents/README.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
