name: Test
on:
  push:
    branches: [main]
jobs:
  cli:
    runs-on: ubuntu-latest
    steps:
      - run: gh api -H "Accept: application/vnd.github.VERSION.raw" /repos/jayground8/poc/contents/README.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
